name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: rg.fr-par.scw.cloud/namespace-quirky-meninsky
        username: nologin
        password: ${{ secrets.SW_SECRET_KEY }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: rg.fr-par.scw.cloud/namespace-quirky-meninsky/sncf-board:latest
